name: Continuous Integration
on:
  push:
    branches:
      - main
jobs:
  test-bb:
    runs-on: ubuntu-latest
    steps:
            - name: Set up ssh-agent
              uses: webfactory/ssh-agent@v0.7.0
              with:
                  ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}
                  
            - name: Checking out this repo
            - uses: actions/checkout@v3
              with:
                fetch-depth: 0
            - name: Git clone
              run: |
                eval `ssh-agent -s`
                ssh-add - <<< '${{ secrets.SSH_PRIVATE_KEY }}'
                ssh-keyscan -t rsa bitbucket.org >> ~/.ssh/known_hosts
                git clone git@bitbucket.org:add3-main/add3-blockchain.git
            
            - name: Ls bb
              run: ls -la
