name: Continuous Integration
on:
  push:
    branches:
      - main
jobs:
  test-bb:
    runs-on: ubuntu-latest
    steps:
            - name: Set up ssh-agent
              uses: webfactory/ssh-agent@v0.7.0
              with:
                  ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}
                  
            - name: Checking out this repo
              uses: actions/checkout@v3
              with:
                fetch-depth: 0
            - name: Git clone
              run: |
                ssh-keyscan -t rsa bitbucket.org >> ~/.ssh/known_hosts
                git clone -b develop git@bitbucket.org:add3-main/add3-blockchain.git
            
            - name: Copy files we want to duplicate
              run: |
                cp -R abi add3-blockchain || true
                cp StakingDynamic.sol add3-blockchain || true
                cp StakingStatic.sol add3-blockchain || true
                cp VestingModule.sol add3-blockchain || true

            - name: Check or a change and push
              working-directory: add3-blockchain
              run: |
                git config --global user.email "nuno@add3.io"
                git config --global user.name "Nuno Cervaens"
                git add .
                git commit -m "testing"
                git push
